### ISSUE TITLE
Why results mush higher than previous works?

### ISSUE THREAD

**Issue by DUT-CSJ** [HanboBizl/DMNet#4]
Thank you for releasing your great work.
I want to know why the performance on isaid-5i in your paper is much higher than SDM (Scale-Aware Detailed Matching for Few-Shot
Aerial Image Semantic Segmentation) or SCCNet (Self-Correlation and Cross-Correlation Learning for Few-Shot Remote Sensing Image Semantic Segmentation)?
Looking forward to  your reply.

**Comment by HanboBizl** [comment]
The scheme for data processing has been described in the experimental setup section of the paper. Following BAM (Base and Meta: A New Perspective on Few-Shot Segmentation), we remove the training images containing the category targets of the testing set to avoid information leakage from the testing set. SDMNet and SCCNet have different data processing schemes than us, which is why we outperform them. You can read about the data processing section in the readme for further details. Welcome to utilize our data.

**Comment by DUT-CSJ** [comment]
Thank you for replying!
